shiny:
  proxy:
    title: ShinyProxy Hello World
    landing-page: /
    heartbeat-rate: 10000
    heartbeat-timeout: 60000
    port: 8080
    authentication: simple
    admin-groups: scientists
    users:
    - name: jack
      password: password
      groups: scientists
    # Docker configuration
    docker:
      cert-path: /home/none
      url: http://localhost:2375
      port-range-start: 20000
  apps:
  - name: hello_world
    display-name: Hello World Application
    description: Good old faithful demo app
    docker-cmd: ["R", "-e", "shiny::runApp('/root/shiny/app')"]
    docker-image: shinyproxy/helloworld
    groups: scientists, mathematicians

logging:
  file:
    shinyproxy.log